{{- if (empty .Values.server.configMapOverrideName) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.server.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prometheus.server.fullname" . }}
data:
          {{- if or .Values.alertmanager.enabled .Values.server.alertmanagerURL }}
          ## I can't find this in the config. I'll figure it out later. This key is madeup.
  alertmanager_config:
            url: {{- if .Values.alertmanager.enabled }}http://{{ template "prometheus.alertmanager.fullname" . }}:{{ .Values.alertmanager.service.servicePort }}{{ .Values.alertmanager.prefixURL }}{{- else }}{{ .Values.server.alertmanagerURL }}{{- end }}
          {{- end }}

          # TODO
          #  {{- if .Values.server.retention }}
          #   - --storage.local.retention={{ .Values.server.retention }}
          # {{- end }}
            # - --storage.local.path={{ .Values.server.persistentVolume.mountPath }}
{{ toYaml .Values.serverFiles | indent 2 }}
{{- end }}
